# coding: utf-8

"""
    Gurufocus Data Package API

    API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.stocks_symbol_fundamentals_get200_response import StocksSymbolFundamentalsGet200Response

class TestStocksSymbolFundamentalsGet200Response(unittest.TestCase):
    """StocksSymbolFundamentalsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StocksSymbolFundamentalsGet200Response:
        """Test StocksSymbolFundamentalsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StocksSymbolFundamentalsGet200Response`
        """
        model = StocksSymbolFundamentalsGet200Response()
        if include_optional:
            return StocksSymbolFundamentalsGet200Response(
                annually = [
                    null
                    ],
                basic_information = openapi_client.models.stock_fundamentals_basic_information.stock_fundamentals_basic_information(
                    company = '', 
                    company_id = '', 
                    exchange = '', 
                    stockid = '', 
                    symbol = '', ),
                quarterly = [
                    null
                    ],
                ttm = openapi_client.models.stock_fundamentals_ttm.stock_fundamentals_ttm()
            )
        else:
            return StocksSymbolFundamentalsGet200Response(
        )
        """

    def testStocksSymbolFundamentalsGet200Response(self):
        """Test StocksSymbolFundamentalsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
