# coding: utf-8

"""
    Gurufocus Data Package API

    API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gurus_id_get200_response import GurusIdGet200Response

class TestGurusIdGet200Response(unittest.TestCase):
    """GurusIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GurusIdGet200Response:
        """Test GurusIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GurusIdGet200Response`
        """
        model = GurusIdGet200Response()
        if include_optional:
            return GurusIdGet200Response(
                var_13_dg = [
                    openapi_client.models.guru_transaction.guru_transaction(
                        action = '', 
                        change = 1.337, 
                        class = '', 
                        comment = '', 
                        company_name = '', 
                        exchange = '', 
                        impact = 1.337, 
                        industry_code = 1.337, 
                        portdate = '', 
                        position = 1.337, 
                        price_avg = 1.337, 
                        price_max = 1.337, 
                        price_min = 1.337, 
                        share_change = 1.337, 
                        shares = 1.337, 
                        shares_outstanding = 1.337, 
                        split_factor = 1.337, 
                        stockid = '', 
                        symbol = '', 
                        value = 1.337, )
                    ],
                var_13_f = [
                    openapi_client.models.guru_transaction.guru_transaction(
                        action = '', 
                        change = 1.337, 
                        class = '', 
                        comment = '', 
                        company_name = '', 
                        exchange = '', 
                        impact = 1.337, 
                        industry_code = 1.337, 
                        portdate = '', 
                        position = 1.337, 
                        price_avg = 1.337, 
                        price_max = 1.337, 
                        price_min = 1.337, 
                        share_change = 1.337, 
                        shares = 1.337, 
                        shares_outstanding = 1.337, 
                        split_factor = 1.337, 
                        stockid = '', 
                        symbol = '', 
                        value = 1.337, )
                    ]
            )
        else:
            return GurusIdGet200Response(
        )
        """

    def testGurusIdGet200Response(self):
        """Test GurusIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
