# coding: utf-8

"""
    Gurufocus Data Package API

    API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.insider_transaction import InsiderTransaction

class TestInsiderTransaction(unittest.TestCase):
    """InsiderTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsiderTransaction:
        """Test InsiderTransaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsiderTransaction`
        """
        model = InsiderTransaction()
        if include_optional:
            return InsiderTransaction(
                cik_reporting = '',
                company = '',
                cost = 1.337,
                var_date = '',
                exchange = '',
                final_share = 1.337,
                name = '',
                position = '',
                price = 1.337,
                split_factor = 1.337,
                stockid = '',
                symbol = '',
                trans_share = 1.337,
                type = ''
            )
        else:
            return InsiderTransaction(
        )
        """

    def testInsiderTransaction(self):
        """Test InsiderTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
