# coding: utf-8

"""
    Gurufocus Data Package API

    API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.valuations_nreitdirect_per_share_data import ValuationsNREITDIRECTPerShareData

class TestValuationsNREITDIRECTPerShareData(unittest.TestCase):
    """ValuationsNREITDIRECTPerShareData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValuationsNREITDIRECTPerShareData:
        """Test ValuationsNREITDIRECTPerShareData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValuationsNREITDIRECTPerShareData`
        """
        model = ValuationsNREITDIRECTPerShareData()
        if include_optional:
            return ValuationsNREITDIRECTPerShareData(
                book_value_per_share = 1.337,
                cash_flow_from_operations_per_share = 1.337,
                cash_per_share = 1.337,
                dividends_per_share = 1.337,
                earning_per_share_diluted = 1.337,
                ebit_per_share = 1.337,
                ebitda_per_share = 1.337,
                eps_without_nri = 1.337,
                ffo_per_share = 1.337,
                free_cash_flow_per_share = 1.337,
                month_end_stock_price = 1.337,
                owner_earnings = 1.337,
                revenue_per_share = 1.337,
                tangibles_book_per_share = 1.337,
                total_debt_per_share = 1.337
            )
        else:
            return ValuationsNREITDIRECTPerShareData(
        )
        """

    def testValuationsNREITDIRECTPerShareData(self):
        """Test ValuationsNREITDIRECTPerShareData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
