/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EtfEtfBasicInformation;
import org.openapitools.client.model.EtfEtfDividends;
import org.openapitools.client.model.EtfEtfFundamental;
import org.openapitools.client.model.EtfEtfKeyStatistics;
import org.openapitools.client.model.EtfEtfPortfolioHoldings;
import org.openapitools.client.model.EtfEtfSectorBreakdowns;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EtfSymbolGet200Response
 */
public class EtfSymbolGet200ResponseTest {
    private final EtfSymbolGet200Response model = new EtfSymbolGet200Response();

    /**
     * Model tests for EtfSymbolGet200Response
     */
    @Test
    public void testEtfSymbolGet200Response() {
        // TODO: test EtfSymbolGet200Response
    }

    /**
     * Test the property 'basicInformation'
     */
    @Test
    public void basicInformationTest() {
        // TODO: test basicInformation
    }

    /**
     * Test the property 'dividends'
     */
    @Test
    public void dividendsTest() {
        // TODO: test dividends
    }

    /**
     * Test the property 'fundamental'
     */
    @Test
    public void fundamentalTest() {
        // TODO: test fundamental
    }

    /**
     * Test the property 'keyStatistics'
     */
    @Test
    public void keyStatisticsTest() {
        // TODO: test keyStatistics
    }

    /**
     * Test the property 'portfolioHoldings'
     */
    @Test
    public void portfolioHoldingsTest() {
        // TODO: test portfolioHoldings
    }

    /**
     * Test the property 'sectorBreakdowns'
     */
    @Test
    public void sectorBreakdownsTest() {
        // TODO: test sectorBreakdowns
    }

}
