/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GuruTransaction
 */
public class GuruTransactionTest {
    private final GuruTransaction model = new GuruTransaction();

    /**
     * Model tests for GuruTransaction
     */
    @Test
    public void testGuruTransaction() {
        // TODO: test GuruTransaction
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'change'
     */
    @Test
    public void changeTest() {
        // TODO: test change
    }

    /**
     * Test the property 'propertyClass'
     */
    @Test
    public void propertyClassTest() {
        // TODO: test propertyClass
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    public void exchangeTest() {
        // TODO: test exchange
    }

    /**
     * Test the property 'impact'
     */
    @Test
    public void impactTest() {
        // TODO: test impact
    }

    /**
     * Test the property 'industryCode'
     */
    @Test
    public void industryCodeTest() {
        // TODO: test industryCode
    }

    /**
     * Test the property 'portdate'
     */
    @Test
    public void portdateTest() {
        // TODO: test portdate
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'priceAvg'
     */
    @Test
    public void priceAvgTest() {
        // TODO: test priceAvg
    }

    /**
     * Test the property 'priceMax'
     */
    @Test
    public void priceMaxTest() {
        // TODO: test priceMax
    }

    /**
     * Test the property 'priceMin'
     */
    @Test
    public void priceMinTest() {
        // TODO: test priceMin
    }

    /**
     * Test the property 'shareChange'
     */
    @Test
    public void shareChangeTest() {
        // TODO: test shareChange
    }

    /**
     * Test the property 'shares'
     */
    @Test
    public void sharesTest() {
        // TODO: test shares
    }

    /**
     * Test the property 'sharesOutstanding'
     */
    @Test
    public void sharesOutstandingTest() {
        // TODO: test sharesOutstanding
    }

    /**
     * Test the property 'splitFactor'
     */
    @Test
    public void splitFactorTest() {
        // TODO: test splitFactor
    }

    /**
     * Test the property 'stockid'
     */
    @Test
    public void stockidTest() {
        // TODO: test stockid
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
