/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StockRankingsGuruFocusRankings
 */
public class StockRankingsGuruFocusRankingsTest {
    private final StockRankingsGuruFocusRankings model = new StockRankingsGuruFocusRankings();

    /**
     * Model tests for StockRankingsGuruFocusRankings
     */
    @Test
    public void testStockRankingsGuruFocusRankings() {
        // TODO: test StockRankingsGuruFocusRankings
    }

    /**
     * Test the property 'gfScore'
     */
    @Test
    public void gfScoreTest() {
        // TODO: test gfScore
    }

    /**
     * Test the property 'gfScoreHigh'
     */
    @Test
    public void gfScoreHighTest() {
        // TODO: test gfScoreHigh
    }

    /**
     * Test the property 'gfScoreLow'
     */
    @Test
    public void gfScoreLowTest() {
        // TODO: test gfScoreLow
    }

    /**
     * Test the property 'gfScoreMed'
     */
    @Test
    public void gfScoreMedTest() {
        // TODO: test gfScoreMed
    }

    /**
     * Test the property 'gfScoreMed5y'
     */
    @Test
    public void gfScoreMed5yTest() {
        // TODO: test gfScoreMed5y
    }

    /**
     * Test the property 'gfValue'
     */
    @Test
    public void gfValueTest() {
        // TODO: test gfValue
    }

    /**
     * Test the property 'gfValueEst'
     */
    @Test
    public void gfValueEstTest() {
        // TODO: test gfValueEst
    }

    /**
     * Test the property 'gfValueEst2nd'
     */
    @Test
    public void gfValueEst2ndTest() {
        // TODO: test gfValueEst2nd
    }

    /**
     * Test the property 'gfValueEst3rd'
     */
    @Test
    public void gfValueEst3rdTest() {
        // TODO: test gfValueEst3rd
    }

    /**
     * Test the property 'gfValuePctChange'
     */
    @Test
    public void gfValuePctChangeTest() {
        // TODO: test gfValuePctChange
    }

    /**
     * Test the property 'marginGfValue'
     */
    @Test
    public void marginGfValueTest() {
        // TODO: test marginGfValue
    }

    /**
     * Test the property 'p2gfValue'
     */
    @Test
    public void p2gfValueTest() {
        // TODO: test p2gfValue
    }

    /**
     * Test the property 'p2gfValueEst'
     */
    @Test
    public void p2gfValueEstTest() {
        // TODO: test p2gfValueEst
    }

    /**
     * Test the property 'p2gfValueHigh'
     */
    @Test
    public void p2gfValueHighTest() {
        // TODO: test p2gfValueHigh
    }

    /**
     * Test the property 'p2gfValueLow'
     */
    @Test
    public void p2gfValueLowTest() {
        // TODO: test p2gfValueLow
    }

    /**
     * Test the property 'p2gfValueMed'
     */
    @Test
    public void p2gfValueMedTest() {
        // TODO: test p2gfValueMed
    }

    /**
     * Test the property 'predictability'
     */
    @Test
    public void predictabilityTest() {
        // TODO: test predictability
    }

    /**
     * Test the property 'rankBalancesheet'
     */
    @Test
    public void rankBalancesheetTest() {
        // TODO: test rankBalancesheet
    }

    /**
     * Test the property 'rankBalancesheetHigh'
     */
    @Test
    public void rankBalancesheetHighTest() {
        // TODO: test rankBalancesheetHigh
    }

    /**
     * Test the property 'rankBalancesheetLow'
     */
    @Test
    public void rankBalancesheetLowTest() {
        // TODO: test rankBalancesheetLow
    }

    /**
     * Test the property 'rankBalancesheetMed'
     */
    @Test
    public void rankBalancesheetMedTest() {
        // TODO: test rankBalancesheetMed
    }

    /**
     * Test the property 'rankGfValue'
     */
    @Test
    public void rankGfValueTest() {
        // TODO: test rankGfValue
    }

    /**
     * Test the property 'rankGfValueHigh'
     */
    @Test
    public void rankGfValueHighTest() {
        // TODO: test rankGfValueHigh
    }

    /**
     * Test the property 'rankGfValueLow'
     */
    @Test
    public void rankGfValueLowTest() {
        // TODO: test rankGfValueLow
    }

    /**
     * Test the property 'rankGrowth'
     */
    @Test
    public void rankGrowthTest() {
        // TODO: test rankGrowth
    }

    /**
     * Test the property 'rankGrowthHigh'
     */
    @Test
    public void rankGrowthHighTest() {
        // TODO: test rankGrowthHigh
    }

    /**
     * Test the property 'rankGrowthLow'
     */
    @Test
    public void rankGrowthLowTest() {
        // TODO: test rankGrowthLow
    }

    /**
     * Test the property 'rankGrowthMed'
     */
    @Test
    public void rankGrowthMedTest() {
        // TODO: test rankGrowthMed
    }

    /**
     * Test the property 'rankMomentum'
     */
    @Test
    public void rankMomentumTest() {
        // TODO: test rankMomentum
    }

    /**
     * Test the property 'rankMomentumHigh'
     */
    @Test
    public void rankMomentumHighTest() {
        // TODO: test rankMomentumHigh
    }

    /**
     * Test the property 'rankMomentumLow'
     */
    @Test
    public void rankMomentumLowTest() {
        // TODO: test rankMomentumLow
    }

    /**
     * Test the property 'rankMomentumMed'
     */
    @Test
    public void rankMomentumMedTest() {
        // TODO: test rankMomentumMed
    }

    /**
     * Test the property 'rankProfitability'
     */
    @Test
    public void rankProfitabilityTest() {
        // TODO: test rankProfitability
    }

    /**
     * Test the property 'rankProfitabilityHigh'
     */
    @Test
    public void rankProfitabilityHighTest() {
        // TODO: test rankProfitabilityHigh
    }

    /**
     * Test the property 'rankProfitabilityLow'
     */
    @Test
    public void rankProfitabilityLowTest() {
        // TODO: test rankProfitabilityLow
    }

    /**
     * Test the property 'rankProfitabilityMed'
     */
    @Test
    public void rankProfitabilityMedTest() {
        // TODO: test rankProfitabilityMed
    }

}
