/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.StockFundamentalsAnnuallyInner;
import org.openapitools.client.model.StockFundamentalsBasicInformation;
import org.openapitools.client.model.StockFundamentalsTtm;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StocksSymbolFundamentalsGet200Response
 */
public class StocksSymbolFundamentalsGet200ResponseTest {
    private final StocksSymbolFundamentalsGet200Response model = new StocksSymbolFundamentalsGet200Response();

    /**
     * Model tests for StocksSymbolFundamentalsGet200Response
     */
    @Test
    public void testStocksSymbolFundamentalsGet200Response() {
        // TODO: test StocksSymbolFundamentalsGet200Response
    }

    /**
     * Test the property 'annually'
     */
    @Test
    public void annuallyTest() {
        // TODO: test annually
    }

    /**
     * Test the property 'basicInformation'
     */
    @Test
    public void basicInformationTest() {
        // TODO: test basicInformation
    }

    /**
     * Test the property 'quarterly'
     */
    @Test
    public void quarterlyTest() {
        // TODO: test quarterly
    }

    /**
     * Test the property 'ttm'
     */
    @Test
    public void ttmTest() {
        // TODO: test ttm
    }

}
