/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValuationsINOREITNODIRECTPerShareData
 */
public class ValuationsINOREITNODIRECTPerShareDataTest {
    private final ValuationsINOREITNODIRECTPerShareData model = new ValuationsINOREITNODIRECTPerShareData();

    /**
     * Model tests for ValuationsINOREITNODIRECTPerShareData
     */
    @Test
    public void testValuationsINOREITNODIRECTPerShareData() {
        // TODO: test ValuationsINOREITNODIRECTPerShareData
    }

    /**
     * Test the property 'bookValuePerShare'
     */
    @Test
    public void bookValuePerShareTest() {
        // TODO: test bookValuePerShare
    }

    /**
     * Test the property 'cashFlowFromOperationsPerShare'
     */
    @Test
    public void cashFlowFromOperationsPerShareTest() {
        // TODO: test cashFlowFromOperationsPerShare
    }

    /**
     * Test the property 'cashPerShare'
     */
    @Test
    public void cashPerShareTest() {
        // TODO: test cashPerShare
    }

    /**
     * Test the property 'dividendsPerShare'
     */
    @Test
    public void dividendsPerShareTest() {
        // TODO: test dividendsPerShare
    }

    /**
     * Test the property 'earningPerShareDiluted'
     */
    @Test
    public void earningPerShareDilutedTest() {
        // TODO: test earningPerShareDiluted
    }

    /**
     * Test the property 'ebitPerShare'
     */
    @Test
    public void ebitPerShareTest() {
        // TODO: test ebitPerShare
    }

    /**
     * Test the property 'ebitdaPerShare'
     */
    @Test
    public void ebitdaPerShareTest() {
        // TODO: test ebitdaPerShare
    }

    /**
     * Test the property 'epsWithoutNri'
     */
    @Test
    public void epsWithoutNriTest() {
        // TODO: test epsWithoutNri
    }

    /**
     * Test the property 'freeCashFlowPerShare'
     */
    @Test
    public void freeCashFlowPerShareTest() {
        // TODO: test freeCashFlowPerShare
    }

    /**
     * Test the property 'monthEndStockPrice'
     */
    @Test
    public void monthEndStockPriceTest() {
        // TODO: test monthEndStockPrice
    }

    /**
     * Test the property 'ownerEarnings'
     */
    @Test
    public void ownerEarningsTest() {
        // TODO: test ownerEarnings
    }

    /**
     * Test the property 'revenuePerShare'
     */
    @Test
    public void revenuePerShareTest() {
        // TODO: test revenuePerShare
    }

    /**
     * Test the property 'tangiblesBookPerShare'
     */
    @Test
    public void tangiblesBookPerShareTest() {
        // TODO: test tangiblesBookPerShare
    }

    /**
     * Test the property 'totalDebtPerShare'
     */
    @Test
    public void totalDebtPerShareTest() {
        // TODO: test totalDebtPerShare
    }

}
