<?php
/**
 * FundamentalsINOREITNODIRECTBalanceSheetTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gurufocus Data Package API
 *
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FundamentalsINOREITNODIRECTBalanceSheetTest Class Doc Comment
 *
 * @category    Class
 * @description FundamentalsINOREITNODIRECTBalanceSheet
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FundamentalsINOREITNODIRECTBalanceSheetTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FundamentalsINOREITNODIRECTBalanceSheet"
     */
    public function testFundamentalsINOREITNODIRECTBalanceSheet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accounts_receivable"
     */
    public function testPropertyAccountsReceivable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accumulated_other_comprehensive_income"
     */
    public function testPropertyAccumulatedOtherComprehensiveIncome()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additional_paid_in_capital"
     */
    public function testPropertyAdditionalPaidInCapital()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_cash_and_cash_equivalents"
     */
    public function testPropertyBsCashAndCashEquivalents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_current_deferred_liabilities"
     */
    public function testPropertyBsCurrentDeferredLiabilities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_deferred_policy_acquisition_costs"
     */
    public function testPropertyBsDeferredPolicyAcquisitionCosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_equity_investments"
     */
    public function testPropertyBsEquityInvestments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_fixed_maturity_investment"
     */
    public function testPropertyBsFixedMaturityInvestment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_future_policy_benefits"
     */
    public function testPropertyBsFuturePolicyBenefits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_net_loan"
     */
    public function testPropertyBsNetLoan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_other_assets_insurance"
     */
    public function testPropertyBsOtherAssetsInsurance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_other_liabilities_insurance"
     */
    public function testPropertyBsOtherLiabilitiesInsurance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_payables_and_accrued_expenses"
     */
    public function testPropertyBsPayablesAndAccruedExpenses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_policyholder_funds"
     */
    public function testPropertyBsPolicyholderFunds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_trading_assets"
     */
    public function testPropertyBsTradingAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_unearned_premiums"
     */
    public function testPropertyBsUnearnedPremiums()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bs_unpaid_loss_and_loss_reserve"
     */
    public function testPropertyBsUnpaidLossAndLossReserve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "common_stock"
     */
    public function testPropertyCommonStock()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_deferred_revenue"
     */
    public function testPropertyCurrentDeferredRevenue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_deferred_taxes_liabilities"
     */
    public function testPropertyCurrentDeferredTaxesLiabilities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "debt_to_equity"
     */
    public function testPropertyDebtToEquity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "equity_to_asset"
     */
    public function testPropertyEquityToAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "good_will"
     */
    public function testPropertyGoodWill()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "intangibles"
     */
    public function testPropertyIntangibles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "long_term_debt_and_capital_lease_obligation"
     */
    public function testPropertyLongTermDebtAndCapitalLeaseObligation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "minority_interest"
     */
    public function testPropertyMinorityInterest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "net_ppe"
     */
    public function testPropertyNetPpe()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "non_current_deferred_income_tax"
     */
    public function testPropertyNonCurrentDeferredIncomeTax()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "non_current_deferred_liabilities"
     */
    public function testPropertyNonCurrentDeferredLiabilities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notes_receivable"
     */
    public function testPropertyNotesReceivable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_current_receivables"
     */
    public function testPropertyOtherCurrentReceivables()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_equity"
     */
    public function testPropertyOtherEquity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preferred_stock"
     */
    public function testPropertyPreferredStock()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "retained_earnings"
     */
    public function testPropertyRetainedEarnings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "short_term_debt_and_capital_lease_obligation"
     */
    public function testPropertyShortTermDebtAndCapitalLeaseObligation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_assets"
     */
    public function testPropertyTotalAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_equity"
     */
    public function testPropertyTotalEquity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_liabilities"
     */
    public function testPropertyTotalLiabilities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_receivables"
     */
    public function testPropertyTotalReceivables()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_stockholders_equity"
     */
    public function testPropertyTotalStockholdersEquity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "treasury_stock"
     */
    public function testPropertyTreasuryStock()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
