<?php
/**
 * ValuationsNNOREITDIRECTRatiosTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gurufocus Data Package API
 *
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ValuationsNNOREITDIRECTRatiosTest Class Doc Comment
 *
 * @category    Class
 * @description ValuationsNNOREITDIRECTRatios
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ValuationsNNOREITDIRECTRatiosTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ValuationsNNOREITDIRECTRatios"
     */
    public function testValuationsNNOREITDIRECTRatios()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "capex_to_operating_cash_flow"
     */
    public function testPropertyCapexToOperatingCashFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "capex_to_operating_income"
     */
    public function testPropertyCapexToOperatingIncome()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "capex_to_revenue"
     */
    public function testPropertyCapexToRevenue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_conversion_cycle"
     */
    public function testPropertyCashConversionCycle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_of_goods_sold_to_revenue"
     */
    public function testPropertyCostOfGoodsSoldToRevenue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "days_inventory"
     */
    public function testPropertyDaysInventory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "days_payable"
     */
    public function testPropertyDaysPayable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "days_sales_outstanding"
     */
    public function testPropertyDaysSalesOutstanding()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "debt_to_asset"
     */
    public function testPropertyDebtToAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "debt_to_equity"
     */
    public function testPropertyDebtToEquity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "degree_of_financial_leverage"
     */
    public function testPropertyDegreeOfFinancialLeverage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "degree_of_operating_leverage"
     */
    public function testPropertyDegreeOfOperatingLeverage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ebitda_margin"
     */
    public function testPropertyEbitdaMargin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "effective_interest_rate"
     */
    public function testPropertyEffectiveInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "equity_to_asset"
     */
    public function testPropertyEquityToAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fcf_margin"
     */
    public function testPropertyFcfMargin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gross_margin"
     */
    public function testPropertyGrossMargin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gross_profit_to_asset"
     */
    public function testPropertyGrossProfitToAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_to_revenue"
     */
    public function testPropertyInventoryToRevenue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_turnover"
     */
    public function testPropertyInventoryTurnover()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liabilities_to_assets"
     */
    public function testPropertyLiabilitiesToAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "net_margin"
     */
    public function testPropertyNetMargin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "operating_margin"
     */
    public function testPropertyOperatingMargin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payout"
     */
    public function testPropertyPayout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rd2rev"
     */
    public function testPropertyRd2rev()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receivables_turnover"
     */
    public function testPropertyReceivablesTurnover()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_on_tangible_asset"
     */
    public function testPropertyReturnOnTangibleAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_on_tangible_equity"
     */
    public function testPropertyReturnOnTangibleEquity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roa"
     */
    public function testPropertyRoa()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roc_joel"
     */
    public function testPropertyRocJoel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roce"
     */
    public function testPropertyRoce()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roe"
     */
    public function testPropertyRoe()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roe_adj"
     */
    public function testPropertyRoeAdj()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roic"
     */
    public function testPropertyRoic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roiic_1y"
     */
    public function testPropertyRoiic1y()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rore_5y"
     */
    public function testPropertyRore5y()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "turnover"
     */
    public function testPropertyTurnover()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wacc"
     */
    public function testPropertyWacc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
