# coding: utf-8

"""
    Gurufocus Data Package API

    API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.guru_transaction import GuruTransaction
from typing import Optional, Set
from typing_extensions import Self

class GurusIdGet200Response(BaseModel):
    """
    GurusIdGet200Response
    """ # noqa: E501
    var_13_dg: Optional[List[GuruTransaction]] = Field(default=None, description="Array of guru transactions", alias="13DG")
    var_13_f: Optional[List[GuruTransaction]] = Field(default=None, description="Array of guru transactions", alias="13F")
    __properties: ClassVar[List[str]] = ["13DG", "13F"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GurusIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in var_13_dg (list)
        _items = []
        if self.var_13_dg:
            for _item_var_13_dg in self.var_13_dg:
                if _item_var_13_dg:
                    _items.append(_item_var_13_dg.to_dict())
            _dict['13DG'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in var_13_f (list)
        _items = []
        if self.var_13_f:
            for _item_var_13_f in self.var_13_f:
                if _item_var_13_f:
                    _items.append(_item_var_13_f.to_dict())
            _dict['13F'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GurusIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "13DG": [GuruTransaction.from_dict(_item) for _item in obj["13DG"]] if obj.get("13DG") is not None else None,
            "13F": [GuruTransaction.from_dict(_item) for _item in obj["13F"]] if obj.get("13F") is not None else None
        })
        return _obj


