# coding: utf-8

"""
    Gurufocus Data Package API

    API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.stock_rankings_basic_information import StockRankingsBasicInformation
from openapi_client.models.stock_rankings_guru_focus_rankings import StockRankingsGuruFocusRankings
from typing import Optional, Set
from typing_extensions import Self

class StocksSymbolRankingsGet200Response(BaseModel):
    """
    StocksSymbolRankingsGet200Response
    """ # noqa: E501
    basic_information: Optional[StockRankingsBasicInformation] = None
    guru_focus_rankings: Optional[StockRankingsGuruFocusRankings] = None
    __properties: ClassVar[List[str]] = ["basic_information", "guru_focus_rankings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StocksSymbolRankingsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of basic_information
        if self.basic_information:
            _dict['basic_information'] = self.basic_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of guru_focus_rankings
        if self.guru_focus_rankings:
            _dict['guru_focus_rankings'] = self.guru_focus_rankings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StocksSymbolRankingsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "basic_information": StockRankingsBasicInformation.from_dict(obj["basic_information"]) if obj.get("basic_information") is not None else None,
            "guru_focus_rankings": StockRankingsGuruFocusRankings.from_dict(obj["guru_focus_rankings"]) if obj.get("guru_focus_rankings") is not None else None
        })
        return _obj


