/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.DownloadListGet403Response;
import org.openapitools.client.model.DownloadListGet404Response;
import org.openapitools.client.model.DownloadListGet500Response;
import org.openapitools.client.model.GurusIdGet200Response;
import org.openapitools.client.model.GurusListGet200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GuruApi
 */
@Disabled
public class GuruApiTest {

    private final GuruApi api = new GuruApi();

    /**
     * Access the holdings and trades of over 4,500 institutional investors, enabling broad market trend analysis or fueling investment research tools with extensive institutional activity data
     *
     * Last four quarters and future: &lt;ul&gt; &lt;li&gt;Quarterly portfolio holdings of the last 4 quarters&lt;/li&gt; &lt;li&gt;13D/G Data of the last 12 months&lt;/li&gt; &lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gurusIdGetTest() throws ApiException {
        BigDecimal id = null;
        GurusIdGet200Response response = api.gurusIdGet(id);
        // TODO: test validations
    }

    /**
     * Get the list of available gurus&#39; basic information
     *
     * Returns the list of available gurus&#39; basic information. You can use this api to map Gurufocus guru id and the id in your own system. The list is sorted by the id. You can use the &#x60;page&#x60; and &#x60;per_page&#x60; parameters to paginate the results.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gurusListGetTest() throws ApiException {
        Integer perPage = null;
        Integer page = null;
        GurusListGet200Response response = api.gurusListGet(perPage, page);
        // TODO: test validations
    }

}
