/*
 * Gurufocus Data Package API
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.StockRankingsBasicInformation;
import org.openapitools.client.model.StockRankingsGuruFocusRankings;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * StocksSymbolRankingsGet200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T01:10:00.357398434Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class StocksSymbolRankingsGet200Response {
  public static final String SERIALIZED_NAME_BASIC_INFORMATION = "basic_information";
  @SerializedName(SERIALIZED_NAME_BASIC_INFORMATION)
  @javax.annotation.Nullable
  private StockRankingsBasicInformation basicInformation;

  public static final String SERIALIZED_NAME_GURU_FOCUS_RANKINGS = "guru_focus_rankings";
  @SerializedName(SERIALIZED_NAME_GURU_FOCUS_RANKINGS)
  @javax.annotation.Nullable
  private StockRankingsGuruFocusRankings guruFocusRankings;

  public StocksSymbolRankingsGet200Response() {
  }

  public StocksSymbolRankingsGet200Response basicInformation(@javax.annotation.Nullable StockRankingsBasicInformation basicInformation) {
    this.basicInformation = basicInformation;
    return this;
  }

  /**
   * Get basicInformation
   * @return basicInformation
   */
  @javax.annotation.Nullable
  public StockRankingsBasicInformation getBasicInformation() {
    return basicInformation;
  }

  public void setBasicInformation(@javax.annotation.Nullable StockRankingsBasicInformation basicInformation) {
    this.basicInformation = basicInformation;
  }


  public StocksSymbolRankingsGet200Response guruFocusRankings(@javax.annotation.Nullable StockRankingsGuruFocusRankings guruFocusRankings) {
    this.guruFocusRankings = guruFocusRankings;
    return this;
  }

  /**
   * Get guruFocusRankings
   * @return guruFocusRankings
   */
  @javax.annotation.Nullable
  public StockRankingsGuruFocusRankings getGuruFocusRankings() {
    return guruFocusRankings;
  }

  public void setGuruFocusRankings(@javax.annotation.Nullable StockRankingsGuruFocusRankings guruFocusRankings) {
    this.guruFocusRankings = guruFocusRankings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StocksSymbolRankingsGet200Response stocksSymbolRankingsGet200Response = (StocksSymbolRankingsGet200Response) o;
    return Objects.equals(this.basicInformation, stocksSymbolRankingsGet200Response.basicInformation) &&
        Objects.equals(this.guruFocusRankings, stocksSymbolRankingsGet200Response.guruFocusRankings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basicInformation, guruFocusRankings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StocksSymbolRankingsGet200Response {\n");
    sb.append("    basicInformation: ").append(toIndentedString(basicInformation)).append("\n");
    sb.append("    guruFocusRankings: ").append(toIndentedString(guruFocusRankings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("basic_information");
    openapiFields.add("guru_focus_rankings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StocksSymbolRankingsGet200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StocksSymbolRankingsGet200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StocksSymbolRankingsGet200Response is not found in the empty JSON string", StocksSymbolRankingsGet200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StocksSymbolRankingsGet200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StocksSymbolRankingsGet200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `basic_information`
      if (jsonObj.get("basic_information") != null && !jsonObj.get("basic_information").isJsonNull()) {
        StockRankingsBasicInformation.validateJsonElement(jsonObj.get("basic_information"));
      }
      // validate the optional field `guru_focus_rankings`
      if (jsonObj.get("guru_focus_rankings") != null && !jsonObj.get("guru_focus_rankings").isJsonNull()) {
        StockRankingsGuruFocusRankings.validateJsonElement(jsonObj.get("guru_focus_rankings"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StocksSymbolRankingsGet200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StocksSymbolRankingsGet200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StocksSymbolRankingsGet200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StocksSymbolRankingsGet200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<StocksSymbolRankingsGet200Response>() {
           @Override
           public void write(JsonWriter out, StocksSymbolRankingsGet200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StocksSymbolRankingsGet200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StocksSymbolRankingsGet200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StocksSymbolRankingsGet200Response
   * @throws IOException if the JSON string is invalid with respect to StocksSymbolRankingsGet200Response
   */
  public static StocksSymbolRankingsGet200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StocksSymbolRankingsGet200Response.class);
  }

  /**
   * Convert an instance of StocksSymbolRankingsGet200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

