<?php
/**
 * EtfEtfDividends
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gurufocus Data Package API
 *
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EtfEtfDividends Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EtfEtfDividends implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'etf_etf_dividends';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dividend_freq' => 'float',
        'next_dividend_payment_date' => 'string',
        'ttm_dividend' => 'float',
        'yield' => 'float',
        'yield_high' => 'float',
        'yield_low' => 'float',
        'yield_med' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dividend_freq' => null,
        'next_dividend_payment_date' => null,
        'ttm_dividend' => null,
        'yield' => null,
        'yield_high' => null,
        'yield_low' => null,
        'yield_med' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'dividend_freq' => false,
        'next_dividend_payment_date' => false,
        'ttm_dividend' => false,
        'yield' => false,
        'yield_high' => false,
        'yield_low' => false,
        'yield_med' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dividend_freq' => 'dividend_freq',
        'next_dividend_payment_date' => 'next_dividend_payment_date',
        'ttm_dividend' => 'ttm_dividend',
        'yield' => 'yield',
        'yield_high' => 'yield_high',
        'yield_low' => 'yield_low',
        'yield_med' => 'yield_med'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dividend_freq' => 'setDividendFreq',
        'next_dividend_payment_date' => 'setNextDividendPaymentDate',
        'ttm_dividend' => 'setTtmDividend',
        'yield' => 'setYield',
        'yield_high' => 'setYieldHigh',
        'yield_low' => 'setYieldLow',
        'yield_med' => 'setYieldMed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dividend_freq' => 'getDividendFreq',
        'next_dividend_payment_date' => 'getNextDividendPaymentDate',
        'ttm_dividend' => 'getTtmDividend',
        'yield' => 'getYield',
        'yield_high' => 'getYieldHigh',
        'yield_low' => 'getYieldLow',
        'yield_med' => 'getYieldMed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('dividend_freq', $data ?? [], null);
        $this->setIfExists('next_dividend_payment_date', $data ?? [], null);
        $this->setIfExists('ttm_dividend', $data ?? [], null);
        $this->setIfExists('yield', $data ?? [], null);
        $this->setIfExists('yield_high', $data ?? [], null);
        $this->setIfExists('yield_low', $data ?? [], null);
        $this->setIfExists('yield_med', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dividend_freq
     *
     * @return float|null
     */
    public function getDividendFreq()
    {
        return $this->container['dividend_freq'];
    }

    /**
     * Sets dividend_freq
     *
     * @param float|null $dividend_freq The number of times a company pays a dividend per year. Example: 4 means quarterly.
     *
     * @return self
     */
    public function setDividendFreq($dividend_freq)
    {
        if (is_null($dividend_freq)) {
            throw new \InvalidArgumentException('non-nullable dividend_freq cannot be null');
        }
        $this->container['dividend_freq'] = $dividend_freq;

        return $this;
    }

    /**
     * Gets next_dividend_payment_date
     *
     * @return string|null
     */
    public function getNextDividendPaymentDate()
    {
        return $this->container['next_dividend_payment_date'];
    }

    /**
     * Sets next_dividend_payment_date
     *
     * @param string|null $next_dividend_payment_date next_dividend_payment_date
     *
     * @return self
     */
    public function setNextDividendPaymentDate($next_dividend_payment_date)
    {
        if (is_null($next_dividend_payment_date)) {
            throw new \InvalidArgumentException('non-nullable next_dividend_payment_date cannot be null');
        }
        $this->container['next_dividend_payment_date'] = $next_dividend_payment_date;

        return $this;
    }

    /**
     * Gets ttm_dividend
     *
     * @return float|null
     */
    public function getTtmDividend()
    {
        return $this->container['ttm_dividend'];
    }

    /**
     * Sets ttm_dividend
     *
     * @param float|null $ttm_dividend The aggregate amount of dividends over the trailing 12 months
     *
     * @return self
     */
    public function setTtmDividend($ttm_dividend)
    {
        if (is_null($ttm_dividend)) {
            throw new \InvalidArgumentException('non-nullable ttm_dividend cannot be null');
        }
        $this->container['ttm_dividend'] = $ttm_dividend;

        return $this;
    }

    /**
     * Gets yield
     *
     * @return float|null
     */
    public function getYield()
    {
        return $this->container['yield'];
    }

    /**
     * Sets yield
     *
     * @param float|null $yield The dividend yield is the ratio of a company's annual dividend compared to its share price.
     *
     * @return self
     */
    public function setYield($yield)
    {
        if (is_null($yield)) {
            throw new \InvalidArgumentException('non-nullable yield cannot be null');
        }
        $this->container['yield'] = $yield;

        return $this;
    }

    /**
     * Gets yield_high
     *
     * @return float|null
     */
    public function getYieldHigh()
    {
        return $this->container['yield_high'];
    }

    /**
     * Sets yield_high
     *
     * @param float|null $yield_high The dividend yield is the ratio of a company's annual dividend compared to its share price.
     *
     * @return self
     */
    public function setYieldHigh($yield_high)
    {
        if (is_null($yield_high)) {
            throw new \InvalidArgumentException('non-nullable yield_high cannot be null');
        }
        $this->container['yield_high'] = $yield_high;

        return $this;
    }

    /**
     * Gets yield_low
     *
     * @return float|null
     */
    public function getYieldLow()
    {
        return $this->container['yield_low'];
    }

    /**
     * Sets yield_low
     *
     * @param float|null $yield_low The dividend yield is the ratio of a company's annual dividend compared to its share price.
     *
     * @return self
     */
    public function setYieldLow($yield_low)
    {
        if (is_null($yield_low)) {
            throw new \InvalidArgumentException('non-nullable yield_low cannot be null');
        }
        $this->container['yield_low'] = $yield_low;

        return $this;
    }

    /**
     * Gets yield_med
     *
     * @return float|null
     */
    public function getYieldMed()
    {
        return $this->container['yield_med'];
    }

    /**
     * Sets yield_med
     *
     * @param float|null $yield_med The dividend yield is the ratio of a company's annual dividend compared to its share price.
     *
     * @return self
     */
    public function setYieldMed($yield_med)
    {
        if (is_null($yield_med)) {
            throw new \InvalidArgumentException('non-nullable yield_med cannot be null');
        }
        $this->container['yield_med'] = $yield_med;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


