<?php
/**
 * EtfSymbolGet200Response
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gurufocus Data Package API
 *
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EtfSymbolGet200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EtfSymbolGet200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_etf__symbol__get_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'basic_information' => '\OpenAPI\Client\Model\EtfEtfBasicInformation',
        'dividends' => '\OpenAPI\Client\Model\EtfEtfDividends',
        'fundamental' => '\OpenAPI\Client\Model\EtfEtfFundamental',
        'key_statistics' => '\OpenAPI\Client\Model\EtfEtfKeyStatistics',
        'portfolio_holdings' => '\OpenAPI\Client\Model\EtfEtfPortfolioHoldings',
        'sector_breakdowns' => '\OpenAPI\Client\Model\EtfEtfSectorBreakdowns'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'basic_information' => null,
        'dividends' => null,
        'fundamental' => null,
        'key_statistics' => null,
        'portfolio_holdings' => null,
        'sector_breakdowns' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'basic_information' => false,
        'dividends' => false,
        'fundamental' => false,
        'key_statistics' => false,
        'portfolio_holdings' => false,
        'sector_breakdowns' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'basic_information' => 'basic_information',
        'dividends' => 'dividends',
        'fundamental' => 'fundamental',
        'key_statistics' => 'key_statistics',
        'portfolio_holdings' => 'portfolio_holdings',
        'sector_breakdowns' => 'sector_breakdowns'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'basic_information' => 'setBasicInformation',
        'dividends' => 'setDividends',
        'fundamental' => 'setFundamental',
        'key_statistics' => 'setKeyStatistics',
        'portfolio_holdings' => 'setPortfolioHoldings',
        'sector_breakdowns' => 'setSectorBreakdowns'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'basic_information' => 'getBasicInformation',
        'dividends' => 'getDividends',
        'fundamental' => 'getFundamental',
        'key_statistics' => 'getKeyStatistics',
        'portfolio_holdings' => 'getPortfolioHoldings',
        'sector_breakdowns' => 'getSectorBreakdowns'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('basic_information', $data ?? [], null);
        $this->setIfExists('dividends', $data ?? [], null);
        $this->setIfExists('fundamental', $data ?? [], null);
        $this->setIfExists('key_statistics', $data ?? [], null);
        $this->setIfExists('portfolio_holdings', $data ?? [], null);
        $this->setIfExists('sector_breakdowns', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets basic_information
     *
     * @return \OpenAPI\Client\Model\EtfEtfBasicInformation|null
     */
    public function getBasicInformation()
    {
        return $this->container['basic_information'];
    }

    /**
     * Sets basic_information
     *
     * @param \OpenAPI\Client\Model\EtfEtfBasicInformation|null $basic_information basic_information
     *
     * @return self
     */
    public function setBasicInformation($basic_information)
    {
        if (is_null($basic_information)) {
            throw new \InvalidArgumentException('non-nullable basic_information cannot be null');
        }
        $this->container['basic_information'] = $basic_information;

        return $this;
    }

    /**
     * Gets dividends
     *
     * @return \OpenAPI\Client\Model\EtfEtfDividends|null
     */
    public function getDividends()
    {
        return $this->container['dividends'];
    }

    /**
     * Sets dividends
     *
     * @param \OpenAPI\Client\Model\EtfEtfDividends|null $dividends dividends
     *
     * @return self
     */
    public function setDividends($dividends)
    {
        if (is_null($dividends)) {
            throw new \InvalidArgumentException('non-nullable dividends cannot be null');
        }
        $this->container['dividends'] = $dividends;

        return $this;
    }

    /**
     * Gets fundamental
     *
     * @return \OpenAPI\Client\Model\EtfEtfFundamental|null
     */
    public function getFundamental()
    {
        return $this->container['fundamental'];
    }

    /**
     * Sets fundamental
     *
     * @param \OpenAPI\Client\Model\EtfEtfFundamental|null $fundamental fundamental
     *
     * @return self
     */
    public function setFundamental($fundamental)
    {
        if (is_null($fundamental)) {
            throw new \InvalidArgumentException('non-nullable fundamental cannot be null');
        }
        $this->container['fundamental'] = $fundamental;

        return $this;
    }

    /**
     * Gets key_statistics
     *
     * @return \OpenAPI\Client\Model\EtfEtfKeyStatistics|null
     */
    public function getKeyStatistics()
    {
        return $this->container['key_statistics'];
    }

    /**
     * Sets key_statistics
     *
     * @param \OpenAPI\Client\Model\EtfEtfKeyStatistics|null $key_statistics key_statistics
     *
     * @return self
     */
    public function setKeyStatistics($key_statistics)
    {
        if (is_null($key_statistics)) {
            throw new \InvalidArgumentException('non-nullable key_statistics cannot be null');
        }
        $this->container['key_statistics'] = $key_statistics;

        return $this;
    }

    /**
     * Gets portfolio_holdings
     *
     * @return \OpenAPI\Client\Model\EtfEtfPortfolioHoldings|null
     */
    public function getPortfolioHoldings()
    {
        return $this->container['portfolio_holdings'];
    }

    /**
     * Sets portfolio_holdings
     *
     * @param \OpenAPI\Client\Model\EtfEtfPortfolioHoldings|null $portfolio_holdings portfolio_holdings
     *
     * @return self
     */
    public function setPortfolioHoldings($portfolio_holdings)
    {
        if (is_null($portfolio_holdings)) {
            throw new \InvalidArgumentException('non-nullable portfolio_holdings cannot be null');
        }
        $this->container['portfolio_holdings'] = $portfolio_holdings;

        return $this;
    }

    /**
     * Gets sector_breakdowns
     *
     * @return \OpenAPI\Client\Model\EtfEtfSectorBreakdowns|null
     */
    public function getSectorBreakdowns()
    {
        return $this->container['sector_breakdowns'];
    }

    /**
     * Sets sector_breakdowns
     *
     * @param \OpenAPI\Client\Model\EtfEtfSectorBreakdowns|null $sector_breakdowns sector_breakdowns
     *
     * @return self
     */
    public function setSectorBreakdowns($sector_breakdowns)
    {
        if (is_null($sector_breakdowns)) {
            throw new \InvalidArgumentException('non-nullable sector_breakdowns cannot be null');
        }
        $this->container['sector_breakdowns'] = $sector_breakdowns;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


