<?php
/**
 * FundamentalsNNOREITNODIRECT
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gurufocus Data Package API
 *
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FundamentalsNNOREITNODIRECT Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FundamentalsNNOREITNODIRECT implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'fundamentals_N_NO_REIT_NO_DIRECT';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'balance_sheet' => '\OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTBalanceSheet',
        'basic_information' => '\OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTBasicInformation',
        'cashflow_statement' => '\OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTCashflowStatement',
        'income_statement' => '\OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTIncomeStatement'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'balance_sheet' => null,
        'basic_information' => null,
        'cashflow_statement' => null,
        'income_statement' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'balance_sheet' => false,
        'basic_information' => false,
        'cashflow_statement' => false,
        'income_statement' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'balance_sheet' => 'balance_sheet',
        'basic_information' => 'basic_information',
        'cashflow_statement' => 'cashflow_statement',
        'income_statement' => 'income_statement'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'balance_sheet' => 'setBalanceSheet',
        'basic_information' => 'setBasicInformation',
        'cashflow_statement' => 'setCashflowStatement',
        'income_statement' => 'setIncomeStatement'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'balance_sheet' => 'getBalanceSheet',
        'basic_information' => 'getBasicInformation',
        'cashflow_statement' => 'getCashflowStatement',
        'income_statement' => 'getIncomeStatement'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('balance_sheet', $data ?? [], null);
        $this->setIfExists('basic_information', $data ?? [], null);
        $this->setIfExists('cashflow_statement', $data ?? [], null);
        $this->setIfExists('income_statement', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets balance_sheet
     *
     * @return \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTBalanceSheet|null
     */
    public function getBalanceSheet()
    {
        return $this->container['balance_sheet'];
    }

    /**
     * Sets balance_sheet
     *
     * @param \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTBalanceSheet|null $balance_sheet balance_sheet
     *
     * @return self
     */
    public function setBalanceSheet($balance_sheet)
    {
        if (is_null($balance_sheet)) {
            throw new \InvalidArgumentException('non-nullable balance_sheet cannot be null');
        }
        $this->container['balance_sheet'] = $balance_sheet;

        return $this;
    }

    /**
     * Gets basic_information
     *
     * @return \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTBasicInformation|null
     */
    public function getBasicInformation()
    {
        return $this->container['basic_information'];
    }

    /**
     * Sets basic_information
     *
     * @param \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTBasicInformation|null $basic_information basic_information
     *
     * @return self
     */
    public function setBasicInformation($basic_information)
    {
        if (is_null($basic_information)) {
            throw new \InvalidArgumentException('non-nullable basic_information cannot be null');
        }
        $this->container['basic_information'] = $basic_information;

        return $this;
    }

    /**
     * Gets cashflow_statement
     *
     * @return \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTCashflowStatement|null
     */
    public function getCashflowStatement()
    {
        return $this->container['cashflow_statement'];
    }

    /**
     * Sets cashflow_statement
     *
     * @param \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTCashflowStatement|null $cashflow_statement cashflow_statement
     *
     * @return self
     */
    public function setCashflowStatement($cashflow_statement)
    {
        if (is_null($cashflow_statement)) {
            throw new \InvalidArgumentException('non-nullable cashflow_statement cannot be null');
        }
        $this->container['cashflow_statement'] = $cashflow_statement;

        return $this;
    }

    /**
     * Gets income_statement
     *
     * @return \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTIncomeStatement|null
     */
    public function getIncomeStatement()
    {
        return $this->container['income_statement'];
    }

    /**
     * Sets income_statement
     *
     * @param \OpenAPI\Client\Model\FundamentalsNNOREITNODIRECTIncomeStatement|null $income_statement income_statement
     *
     * @return self
     */
    public function setIncomeStatement($income_statement)
    {
        if (is_null($income_statement)) {
            throw new \InvalidArgumentException('non-nullable income_statement cannot be null');
        }
        $this->container['income_statement'] = $income_statement;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


