<?php
/**
 * FundamentalsINOREITNODIRECTCashflowStatement
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gurufocus Data Package API
 *
 * API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FundamentalsINOREITNODIRECTCashflowStatement Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FundamentalsINOREITNODIRECTCashflowStatement implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'fundamentals_I_NO_REIT_NO_DIRECT_cashflow_statement';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'asset_impairment_charge' => 'float',
        'beginning_cash_position' => 'float',
        'cash_flow_capital_expenditure' => 'float',
        'cash_flow_deferred_tax' => 'float',
        'cash_flow_depreciation_depletion_amortization' => 'float',
        'cash_flow_for_lease_financing' => 'float',
        'cash_flow_from_investing' => 'float',
        'cash_flow_from_operations' => 'float',
        'cash_flow_from_others' => 'float',
        'cash_from_discontinued_investing_activities' => 'float',
        'cash_from_discontinued_operating_activities' => 'float',
        'cash_from_financing' => 'float',
        'cash_from_other_investing_activities' => 'float',
        'change_in_inventory' => 'float',
        'change_in_other_working_capital' => 'float',
        'change_in_payables_and_accrued_expense' => 'float',
        'change_in_prepaid_assets' => 'float',
        'change_in_receivables' => 'float',
        'change_in_working_capital' => 'float',
        'debt_issuance' => 'float',
        'debt_payments' => 'float',
        'dividends' => 'float',
        'effect_of_exchange_rate_changes' => 'float',
        'ending_cash_position' => 'float',
        'issuance_of_stock' => 'float',
        'net_change_in_cash' => 'float',
        'net_income_from_continuing_operations' => 'float',
        'net_intangibles_purchase_and_sale' => 'float',
        'net_issuance_of_debt' => 'float',
        'net_issuance_of_preferred' => 'float',
        'other_financing' => 'float',
        'purchase_of_business' => 'float',
        'purchase_of_investment' => 'float',
        'purchase_of_ppe' => 'float',
        'repurchase_of_stock' => 'float',
        'sale_of_business' => 'float',
        'sale_of_investment' => 'float',
        'sale_of_ppe' => 'float',
        'stock_based_compensation' => 'float',
        'total_free_cash_flow' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'asset_impairment_charge' => null,
        'beginning_cash_position' => null,
        'cash_flow_capital_expenditure' => null,
        'cash_flow_deferred_tax' => null,
        'cash_flow_depreciation_depletion_amortization' => null,
        'cash_flow_for_lease_financing' => null,
        'cash_flow_from_investing' => null,
        'cash_flow_from_operations' => null,
        'cash_flow_from_others' => null,
        'cash_from_discontinued_investing_activities' => null,
        'cash_from_discontinued_operating_activities' => null,
        'cash_from_financing' => null,
        'cash_from_other_investing_activities' => null,
        'change_in_inventory' => null,
        'change_in_other_working_capital' => null,
        'change_in_payables_and_accrued_expense' => null,
        'change_in_prepaid_assets' => null,
        'change_in_receivables' => null,
        'change_in_working_capital' => null,
        'debt_issuance' => null,
        'debt_payments' => null,
        'dividends' => null,
        'effect_of_exchange_rate_changes' => null,
        'ending_cash_position' => null,
        'issuance_of_stock' => null,
        'net_change_in_cash' => null,
        'net_income_from_continuing_operations' => null,
        'net_intangibles_purchase_and_sale' => null,
        'net_issuance_of_debt' => null,
        'net_issuance_of_preferred' => null,
        'other_financing' => null,
        'purchase_of_business' => null,
        'purchase_of_investment' => null,
        'purchase_of_ppe' => null,
        'repurchase_of_stock' => null,
        'sale_of_business' => null,
        'sale_of_investment' => null,
        'sale_of_ppe' => null,
        'stock_based_compensation' => null,
        'total_free_cash_flow' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'asset_impairment_charge' => false,
        'beginning_cash_position' => false,
        'cash_flow_capital_expenditure' => false,
        'cash_flow_deferred_tax' => false,
        'cash_flow_depreciation_depletion_amortization' => false,
        'cash_flow_for_lease_financing' => false,
        'cash_flow_from_investing' => false,
        'cash_flow_from_operations' => false,
        'cash_flow_from_others' => false,
        'cash_from_discontinued_investing_activities' => false,
        'cash_from_discontinued_operating_activities' => false,
        'cash_from_financing' => false,
        'cash_from_other_investing_activities' => false,
        'change_in_inventory' => false,
        'change_in_other_working_capital' => false,
        'change_in_payables_and_accrued_expense' => false,
        'change_in_prepaid_assets' => false,
        'change_in_receivables' => false,
        'change_in_working_capital' => false,
        'debt_issuance' => false,
        'debt_payments' => false,
        'dividends' => false,
        'effect_of_exchange_rate_changes' => false,
        'ending_cash_position' => false,
        'issuance_of_stock' => false,
        'net_change_in_cash' => false,
        'net_income_from_continuing_operations' => false,
        'net_intangibles_purchase_and_sale' => false,
        'net_issuance_of_debt' => false,
        'net_issuance_of_preferred' => false,
        'other_financing' => false,
        'purchase_of_business' => false,
        'purchase_of_investment' => false,
        'purchase_of_ppe' => false,
        'repurchase_of_stock' => false,
        'sale_of_business' => false,
        'sale_of_investment' => false,
        'sale_of_ppe' => false,
        'stock_based_compensation' => false,
        'total_free_cash_flow' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'asset_impairment_charge' => 'asset_impairment_charge',
        'beginning_cash_position' => 'beginning_cash_position',
        'cash_flow_capital_expenditure' => 'cash_flow_capital_expenditure',
        'cash_flow_deferred_tax' => 'cash_flow_deferred_tax',
        'cash_flow_depreciation_depletion_amortization' => 'cash_flow_depreciation_depletion_amortization',
        'cash_flow_for_lease_financing' => 'cash_flow_for_lease_financing',
        'cash_flow_from_investing' => 'cash_flow_from_investing',
        'cash_flow_from_operations' => 'cash_flow_from_operations',
        'cash_flow_from_others' => 'cash_flow_from_others',
        'cash_from_discontinued_investing_activities' => 'cash_from_discontinued_investing_activities',
        'cash_from_discontinued_operating_activities' => 'cash_from_discontinued_operating_activities',
        'cash_from_financing' => 'cash_from_financing',
        'cash_from_other_investing_activities' => 'cash_from_other_investing_activities',
        'change_in_inventory' => 'change_in_inventory',
        'change_in_other_working_capital' => 'change_in_other_working_capital',
        'change_in_payables_and_accrued_expense' => 'change_in_payables_and_accrued_expense',
        'change_in_prepaid_assets' => 'change_in_prepaid_assets',
        'change_in_receivables' => 'change_in_receivables',
        'change_in_working_capital' => 'change_in_working_capital',
        'debt_issuance' => 'debt_issuance',
        'debt_payments' => 'debt_payments',
        'dividends' => 'dividends',
        'effect_of_exchange_rate_changes' => 'effect_of_exchange_rate_changes',
        'ending_cash_position' => 'ending_cash_position',
        'issuance_of_stock' => 'issuance_of_stock',
        'net_change_in_cash' => 'net_change_in_cash',
        'net_income_from_continuing_operations' => 'net_income_from_continuing_operations',
        'net_intangibles_purchase_and_sale' => 'net_intangibles_purchase_and_sale',
        'net_issuance_of_debt' => 'net_issuance_of_debt',
        'net_issuance_of_preferred' => 'net_issuance_of_preferred',
        'other_financing' => 'other_financing',
        'purchase_of_business' => 'purchase_of_business',
        'purchase_of_investment' => 'purchase_of_investment',
        'purchase_of_ppe' => 'purchase_of_ppe',
        'repurchase_of_stock' => 'repurchase_of_stock',
        'sale_of_business' => 'sale_of_business',
        'sale_of_investment' => 'sale_of_investment',
        'sale_of_ppe' => 'sale_of_ppe',
        'stock_based_compensation' => 'stock_based_compensation',
        'total_free_cash_flow' => 'total_free_cash_flow'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'asset_impairment_charge' => 'setAssetImpairmentCharge',
        'beginning_cash_position' => 'setBeginningCashPosition',
        'cash_flow_capital_expenditure' => 'setCashFlowCapitalExpenditure',
        'cash_flow_deferred_tax' => 'setCashFlowDeferredTax',
        'cash_flow_depreciation_depletion_amortization' => 'setCashFlowDepreciationDepletionAmortization',
        'cash_flow_for_lease_financing' => 'setCashFlowForLeaseFinancing',
        'cash_flow_from_investing' => 'setCashFlowFromInvesting',
        'cash_flow_from_operations' => 'setCashFlowFromOperations',
        'cash_flow_from_others' => 'setCashFlowFromOthers',
        'cash_from_discontinued_investing_activities' => 'setCashFromDiscontinuedInvestingActivities',
        'cash_from_discontinued_operating_activities' => 'setCashFromDiscontinuedOperatingActivities',
        'cash_from_financing' => 'setCashFromFinancing',
        'cash_from_other_investing_activities' => 'setCashFromOtherInvestingActivities',
        'change_in_inventory' => 'setChangeInInventory',
        'change_in_other_working_capital' => 'setChangeInOtherWorkingCapital',
        'change_in_payables_and_accrued_expense' => 'setChangeInPayablesAndAccruedExpense',
        'change_in_prepaid_assets' => 'setChangeInPrepaidAssets',
        'change_in_receivables' => 'setChangeInReceivables',
        'change_in_working_capital' => 'setChangeInWorkingCapital',
        'debt_issuance' => 'setDebtIssuance',
        'debt_payments' => 'setDebtPayments',
        'dividends' => 'setDividends',
        'effect_of_exchange_rate_changes' => 'setEffectOfExchangeRateChanges',
        'ending_cash_position' => 'setEndingCashPosition',
        'issuance_of_stock' => 'setIssuanceOfStock',
        'net_change_in_cash' => 'setNetChangeInCash',
        'net_income_from_continuing_operations' => 'setNetIncomeFromContinuingOperations',
        'net_intangibles_purchase_and_sale' => 'setNetIntangiblesPurchaseAndSale',
        'net_issuance_of_debt' => 'setNetIssuanceOfDebt',
        'net_issuance_of_preferred' => 'setNetIssuanceOfPreferred',
        'other_financing' => 'setOtherFinancing',
        'purchase_of_business' => 'setPurchaseOfBusiness',
        'purchase_of_investment' => 'setPurchaseOfInvestment',
        'purchase_of_ppe' => 'setPurchaseOfPpe',
        'repurchase_of_stock' => 'setRepurchaseOfStock',
        'sale_of_business' => 'setSaleOfBusiness',
        'sale_of_investment' => 'setSaleOfInvestment',
        'sale_of_ppe' => 'setSaleOfPpe',
        'stock_based_compensation' => 'setStockBasedCompensation',
        'total_free_cash_flow' => 'setTotalFreeCashFlow'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'asset_impairment_charge' => 'getAssetImpairmentCharge',
        'beginning_cash_position' => 'getBeginningCashPosition',
        'cash_flow_capital_expenditure' => 'getCashFlowCapitalExpenditure',
        'cash_flow_deferred_tax' => 'getCashFlowDeferredTax',
        'cash_flow_depreciation_depletion_amortization' => 'getCashFlowDepreciationDepletionAmortization',
        'cash_flow_for_lease_financing' => 'getCashFlowForLeaseFinancing',
        'cash_flow_from_investing' => 'getCashFlowFromInvesting',
        'cash_flow_from_operations' => 'getCashFlowFromOperations',
        'cash_flow_from_others' => 'getCashFlowFromOthers',
        'cash_from_discontinued_investing_activities' => 'getCashFromDiscontinuedInvestingActivities',
        'cash_from_discontinued_operating_activities' => 'getCashFromDiscontinuedOperatingActivities',
        'cash_from_financing' => 'getCashFromFinancing',
        'cash_from_other_investing_activities' => 'getCashFromOtherInvestingActivities',
        'change_in_inventory' => 'getChangeInInventory',
        'change_in_other_working_capital' => 'getChangeInOtherWorkingCapital',
        'change_in_payables_and_accrued_expense' => 'getChangeInPayablesAndAccruedExpense',
        'change_in_prepaid_assets' => 'getChangeInPrepaidAssets',
        'change_in_receivables' => 'getChangeInReceivables',
        'change_in_working_capital' => 'getChangeInWorkingCapital',
        'debt_issuance' => 'getDebtIssuance',
        'debt_payments' => 'getDebtPayments',
        'dividends' => 'getDividends',
        'effect_of_exchange_rate_changes' => 'getEffectOfExchangeRateChanges',
        'ending_cash_position' => 'getEndingCashPosition',
        'issuance_of_stock' => 'getIssuanceOfStock',
        'net_change_in_cash' => 'getNetChangeInCash',
        'net_income_from_continuing_operations' => 'getNetIncomeFromContinuingOperations',
        'net_intangibles_purchase_and_sale' => 'getNetIntangiblesPurchaseAndSale',
        'net_issuance_of_debt' => 'getNetIssuanceOfDebt',
        'net_issuance_of_preferred' => 'getNetIssuanceOfPreferred',
        'other_financing' => 'getOtherFinancing',
        'purchase_of_business' => 'getPurchaseOfBusiness',
        'purchase_of_investment' => 'getPurchaseOfInvestment',
        'purchase_of_ppe' => 'getPurchaseOfPpe',
        'repurchase_of_stock' => 'getRepurchaseOfStock',
        'sale_of_business' => 'getSaleOfBusiness',
        'sale_of_investment' => 'getSaleOfInvestment',
        'sale_of_ppe' => 'getSaleOfPpe',
        'stock_based_compensation' => 'getStockBasedCompensation',
        'total_free_cash_flow' => 'getTotalFreeCashFlow'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('asset_impairment_charge', $data ?? [], null);
        $this->setIfExists('beginning_cash_position', $data ?? [], null);
        $this->setIfExists('cash_flow_capital_expenditure', $data ?? [], null);
        $this->setIfExists('cash_flow_deferred_tax', $data ?? [], null);
        $this->setIfExists('cash_flow_depreciation_depletion_amortization', $data ?? [], null);
        $this->setIfExists('cash_flow_for_lease_financing', $data ?? [], null);
        $this->setIfExists('cash_flow_from_investing', $data ?? [], null);
        $this->setIfExists('cash_flow_from_operations', $data ?? [], null);
        $this->setIfExists('cash_flow_from_others', $data ?? [], null);
        $this->setIfExists('cash_from_discontinued_investing_activities', $data ?? [], null);
        $this->setIfExists('cash_from_discontinued_operating_activities', $data ?? [], null);
        $this->setIfExists('cash_from_financing', $data ?? [], null);
        $this->setIfExists('cash_from_other_investing_activities', $data ?? [], null);
        $this->setIfExists('change_in_inventory', $data ?? [], null);
        $this->setIfExists('change_in_other_working_capital', $data ?? [], null);
        $this->setIfExists('change_in_payables_and_accrued_expense', $data ?? [], null);
        $this->setIfExists('change_in_prepaid_assets', $data ?? [], null);
        $this->setIfExists('change_in_receivables', $data ?? [], null);
        $this->setIfExists('change_in_working_capital', $data ?? [], null);
        $this->setIfExists('debt_issuance', $data ?? [], null);
        $this->setIfExists('debt_payments', $data ?? [], null);
        $this->setIfExists('dividends', $data ?? [], null);
        $this->setIfExists('effect_of_exchange_rate_changes', $data ?? [], null);
        $this->setIfExists('ending_cash_position', $data ?? [], null);
        $this->setIfExists('issuance_of_stock', $data ?? [], null);
        $this->setIfExists('net_change_in_cash', $data ?? [], null);
        $this->setIfExists('net_income_from_continuing_operations', $data ?? [], null);
        $this->setIfExists('net_intangibles_purchase_and_sale', $data ?? [], null);
        $this->setIfExists('net_issuance_of_debt', $data ?? [], null);
        $this->setIfExists('net_issuance_of_preferred', $data ?? [], null);
        $this->setIfExists('other_financing', $data ?? [], null);
        $this->setIfExists('purchase_of_business', $data ?? [], null);
        $this->setIfExists('purchase_of_investment', $data ?? [], null);
        $this->setIfExists('purchase_of_ppe', $data ?? [], null);
        $this->setIfExists('repurchase_of_stock', $data ?? [], null);
        $this->setIfExists('sale_of_business', $data ?? [], null);
        $this->setIfExists('sale_of_investment', $data ?? [], null);
        $this->setIfExists('sale_of_ppe', $data ?? [], null);
        $this->setIfExists('stock_based_compensation', $data ?? [], null);
        $this->setIfExists('total_free_cash_flow', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets asset_impairment_charge
     *
     * @return float|null
     */
    public function getAssetImpairmentCharge()
    {
        return $this->container['asset_impairment_charge'];
    }

    /**
     * Sets asset_impairment_charge
     *
     * @param float|null $asset_impairment_charge asset_impairment_charge
     *
     * @return self
     */
    public function setAssetImpairmentCharge($asset_impairment_charge)
    {
        if (is_null($asset_impairment_charge)) {
            throw new \InvalidArgumentException('non-nullable asset_impairment_charge cannot be null');
        }
        $this->container['asset_impairment_charge'] = $asset_impairment_charge;

        return $this;
    }

    /**
     * Gets beginning_cash_position
     *
     * @return float|null
     */
    public function getBeginningCashPosition()
    {
        return $this->container['beginning_cash_position'];
    }

    /**
     * Sets beginning_cash_position
     *
     * @param float|null $beginning_cash_position beginning_cash_position
     *
     * @return self
     */
    public function setBeginningCashPosition($beginning_cash_position)
    {
        if (is_null($beginning_cash_position)) {
            throw new \InvalidArgumentException('non-nullable beginning_cash_position cannot be null');
        }
        $this->container['beginning_cash_position'] = $beginning_cash_position;

        return $this;
    }

    /**
     * Gets cash_flow_capital_expenditure
     *
     * @return float|null
     */
    public function getCashFlowCapitalExpenditure()
    {
        return $this->container['cash_flow_capital_expenditure'];
    }

    /**
     * Sets cash_flow_capital_expenditure
     *
     * @param float|null $cash_flow_capital_expenditure <p>{{Cash_Flow_CPEX}} refers to the funds spent for a company to acquire or upgrade physical assets such as property, industrial buildings or equipment.</p>
     *
     * @return self
     */
    public function setCashFlowCapitalExpenditure($cash_flow_capital_expenditure)
    {
        if (is_null($cash_flow_capital_expenditure)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_capital_expenditure cannot be null');
        }
        $this->container['cash_flow_capital_expenditure'] = $cash_flow_capital_expenditure;

        return $this;
    }

    /**
     * Gets cash_flow_deferred_tax
     *
     * @return float|null
     */
    public function getCashFlowDeferredTax()
    {
        return $this->container['cash_flow_deferred_tax'];
    }

    /**
     * Sets cash_flow_deferred_tax
     *
     * @param float|null $cash_flow_deferred_tax <p>{{CF_DeferredTax}} represents future tax liability or asset, resulting from temporary differences between book (accounting) value of assets and liabilities, and their tax value. This arises due to differences between financial accounting for shareholders and tax accounting.</p>
     *
     * @return self
     */
    public function setCashFlowDeferredTax($cash_flow_deferred_tax)
    {
        if (is_null($cash_flow_deferred_tax)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_deferred_tax cannot be null');
        }
        $this->container['cash_flow_deferred_tax'] = $cash_flow_deferred_tax;

        return $this;
    }

    /**
     * Gets cash_flow_depreciation_depletion_amortization
     *
     * @return float|null
     */
    public function getCashFlowDepreciationDepletionAmortization()
    {
        return $this->container['cash_flow_depreciation_depletion_amortization'];
    }

    /**
     * Sets cash_flow_depreciation_depletion_amortization
     *
     * @param float|null $cash_flow_depreciation_depletion_amortization <p>{{DDA}} is a present expense that accounts for the past cost of an asset that is now providing benefits. Depletion and amortization are synonyms for depreciation. Generally: The term depreciation is used when discussing man made tangible assets. The term depletion is used when discussing natural tangible assets. The term amortization is used when discussing intangible assets</p>
     *
     * @return self
     */
    public function setCashFlowDepreciationDepletionAmortization($cash_flow_depreciation_depletion_amortization)
    {
        if (is_null($cash_flow_depreciation_depletion_amortization)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_depreciation_depletion_amortization cannot be null');
        }
        $this->container['cash_flow_depreciation_depletion_amortization'] = $cash_flow_depreciation_depletion_amortization;

        return $this;
    }

    /**
     * Gets cash_flow_for_lease_financing
     *
     * @return float|null
     */
    public function getCashFlowForLeaseFinancing()
    {
        return $this->container['cash_flow_for_lease_financing'];
    }

    /**
     * Sets cash_flow_for_lease_financing
     *
     * @param float|null $cash_flow_for_lease_financing https://www.gurufocus.com/glossary/cash_flow_for_lease_financing
     *
     * @return self
     */
    public function setCashFlowForLeaseFinancing($cash_flow_for_lease_financing)
    {
        if (is_null($cash_flow_for_lease_financing)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_for_lease_financing cannot be null');
        }
        $this->container['cash_flow_for_lease_financing'] = $cash_flow_for_lease_financing;

        return $this;
    }

    /**
     * Gets cash_flow_from_investing
     *
     * @return float|null
     */
    public function getCashFlowFromInvesting()
    {
        return $this->container['cash_flow_from_investing'];
    }

    /**
     * Sets cash_flow_from_investing
     *
     * @param float|null $cash_flow_from_investing <p>{{Cash_Flow_from_Investing}} covers the cash a company gains or spends from investment activities in financial market and operating subsidiaries. It also includes the cash the company used for {{Net_PPE}}(PPE). If a company spends cash on {{Net_PPE}} (PPE), this will reduce their cash position. This is called {{Cash_Flow_CPEX}} (CPEX). Likewise, if a company buys another company for cash, this will reduce their cash position. <br>{{Cash_Flow_from_Investing}} is calculated as {{Cash_Flow_from_Investing}} = {{PurchaseOfPPE}} + {{SaleOfPPE}} + {{PurchaseOfBusiness}} + {{SaleOfBusiness}} + {{PurchaseOfInvestment}} + {{SaleOfInvestment}} + {{NetIntangiblesPurchaseAndSale}} + {{CashFromDiscontinuedInvestingActivities}} + {{CashFromOtherInvestingActivities}}</p>
     *
     * @return self
     */
    public function setCashFlowFromInvesting($cash_flow_from_investing)
    {
        if (is_null($cash_flow_from_investing)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_from_investing cannot be null');
        }
        $this->container['cash_flow_from_investing'] = $cash_flow_from_investing;

        return $this;
    }

    /**
     * Gets cash_flow_from_operations
     *
     * @return float|null
     */
    public function getCashFlowFromOperations()
    {
        return $this->container['cash_flow_from_operations'];
    }

    /**
     * Sets cash_flow_from_operations
     *
     * @param float|null $cash_flow_from_operations <p>{{Cash_Flow_from_Operations}} refers to the cash brought in through a company's sales. <br>Therefore, {{Cash_Flow_from_Operations}} = {{NetIncomeFromContinuingOperations}} + {{CF_DDA}} + {ChangeInWorkingCapital}} + Deferred Tax + {{Cash_Flow_from_Disc_Op}} + {{AssetImpairmentCharge}} + {{StockBasedCompensation}} + {{Cash_Flow_from_Others}}</p>
     *
     * @return self
     */
    public function setCashFlowFromOperations($cash_flow_from_operations)
    {
        if (is_null($cash_flow_from_operations)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_from_operations cannot be null');
        }
        $this->container['cash_flow_from_operations'] = $cash_flow_from_operations;

        return $this;
    }

    /**
     * Gets cash_flow_from_others
     *
     * @return float|null
     */
    public function getCashFlowFromOthers()
    {
        return $this->container['cash_flow_from_others'];
    }

    /**
     * Sets cash_flow_from_others
     *
     * @param float|null $cash_flow_from_others <p>{{Cash_Flow_from_Others}} may include {{ChangeInWorkingCapital}}. These are cash differences caused by the {{ChangeInInventory}}, {{AccountsPayable}}, {{Accts_Rec}} etc. For instance, if a company pays its suppliers slower, its cash position will build up faster. If a company receives payments from its customers slower, its {{Accts_Rec}} will rise, and its cash position will grow more slowly (or even shrink).</p>
     *
     * @return self
     */
    public function setCashFlowFromOthers($cash_flow_from_others)
    {
        if (is_null($cash_flow_from_others)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_from_others cannot be null');
        }
        $this->container['cash_flow_from_others'] = $cash_flow_from_others;

        return $this;
    }

    /**
     * Gets cash_from_discontinued_investing_activities
     *
     * @return float|null
     */
    public function getCashFromDiscontinuedInvestingActivities()
    {
        return $this->container['cash_from_discontinued_investing_activities'];
    }

    /**
     * Sets cash_from_discontinued_investing_activities
     *
     * @param float|null $cash_from_discontinued_investing_activities <p>{{CashFromDiscontinuedInvestingActivities}} means the cash received by a company that comes from the discontinued investing activities.</p>
     *
     * @return self
     */
    public function setCashFromDiscontinuedInvestingActivities($cash_from_discontinued_investing_activities)
    {
        if (is_null($cash_from_discontinued_investing_activities)) {
            throw new \InvalidArgumentException('non-nullable cash_from_discontinued_investing_activities cannot be null');
        }
        $this->container['cash_from_discontinued_investing_activities'] = $cash_from_discontinued_investing_activities;

        return $this;
    }

    /**
     * Gets cash_from_discontinued_operating_activities
     *
     * @return float|null
     */
    public function getCashFromDiscontinuedOperatingActivities()
    {
        return $this->container['cash_from_discontinued_operating_activities'];
    }

    /**
     * Sets cash_from_discontinued_operating_activities
     *
     * @param float|null $cash_from_discontinued_operating_activities The cash generated from discontinued operations
     *
     * @return self
     */
    public function setCashFromDiscontinuedOperatingActivities($cash_from_discontinued_operating_activities)
    {
        if (is_null($cash_from_discontinued_operating_activities)) {
            throw new \InvalidArgumentException('non-nullable cash_from_discontinued_operating_activities cannot be null');
        }
        $this->container['cash_from_discontinued_operating_activities'] = $cash_from_discontinued_operating_activities;

        return $this;
    }

    /**
     * Gets cash_from_financing
     *
     * @return float|null
     */
    public function getCashFromFinancing()
    {
        return $this->container['cash_from_financing'];
    }

    /**
     * Sets cash_from_financing
     *
     * @param float|null $cash_from_financing <p>{{Cash_from_Financing}} is the cash generated/spent from financial activities such as share issuance (buy back), debt issuance (repayment), and dividends paid to preferred and common stockholders. In the calculation of {{total_freecashflow}}, {{Cash_from_Financing}} is not calculated because it is not related to operating activities. <br>{{Cash_from_Financing}} = {{Issuance_of_Stock}} + {{Repurchase_of_Stock}} + {{Net_Issuance_of_Debt}} + {{Net_Issuance_of_preferred}} + {{Dividends}} + Other Financing</p>
     *
     * @return self
     */
    public function setCashFromFinancing($cash_from_financing)
    {
        if (is_null($cash_from_financing)) {
            throw new \InvalidArgumentException('non-nullable cash_from_financing cannot be null');
        }
        $this->container['cash_from_financing'] = $cash_from_financing;

        return $this;
    }

    /**
     * Gets cash_from_other_investing_activities
     *
     * @return float|null
     */
    public function getCashFromOtherInvestingActivities()
    {
        return $this->container['cash_from_other_investing_activities'];
    }

    /**
     * Sets cash_from_other_investing_activities
     *
     * @param float|null $cash_from_other_investing_activities <p>{{CashFromOtherInvestingActivities}} means the cash received by a company that comes from other investing activities.</p>
     *
     * @return self
     */
    public function setCashFromOtherInvestingActivities($cash_from_other_investing_activities)
    {
        if (is_null($cash_from_other_investing_activities)) {
            throw new \InvalidArgumentException('non-nullable cash_from_other_investing_activities cannot be null');
        }
        $this->container['cash_from_other_investing_activities'] = $cash_from_other_investing_activities;

        return $this;
    }

    /**
     * Gets change_in_inventory
     *
     * @return float|null
     */
    public function getChangeInInventory()
    {
        return $this->container['change_in_inventory'];
    }

    /**
     * Sets change_in_inventory
     *
     * @param float|null $change_in_inventory <p>{{ChangeInInventory}} is the difference between last period's ending inventory and the current period's ending inventory.</p>
     *
     * @return self
     */
    public function setChangeInInventory($change_in_inventory)
    {
        if (is_null($change_in_inventory)) {
            throw new \InvalidArgumentException('non-nullable change_in_inventory cannot be null');
        }
        $this->container['change_in_inventory'] = $change_in_inventory;

        return $this;
    }

    /**
     * Gets change_in_other_working_capital
     *
     * @return float|null
     */
    public function getChangeInOtherWorkingCapital()
    {
        return $this->container['change_in_other_working_capital'];
    }

    /**
     * Sets change_in_other_working_capital
     *
     * @param float|null $change_in_other_working_capital change_in_other_working_capital
     *
     * @return self
     */
    public function setChangeInOtherWorkingCapital($change_in_other_working_capital)
    {
        if (is_null($change_in_other_working_capital)) {
            throw new \InvalidArgumentException('non-nullable change_in_other_working_capital cannot be null');
        }
        $this->container['change_in_other_working_capital'] = $change_in_other_working_capital;

        return $this;
    }

    /**
     * Gets change_in_payables_and_accrued_expense
     *
     * @return float|null
     */
    public function getChangeInPayablesAndAccruedExpense()
    {
        return $this->container['change_in_payables_and_accrued_expense'];
    }

    /**
     * Sets change_in_payables_and_accrued_expense
     *
     * @param float|null $change_in_payables_and_accrued_expense <p>{{ChangeInPayablesAndAccruedExpense}} is the increase or decrease between periods of the {{Accts_Payable}}. Accrued expenses represent expenses incurred at the end of the reporting period but not yet paid; also called accrued liabilities. The accrued liability is shown under Liabilities section in the balance sheet.</p>
     *
     * @return self
     */
    public function setChangeInPayablesAndAccruedExpense($change_in_payables_and_accrued_expense)
    {
        if (is_null($change_in_payables_and_accrued_expense)) {
            throw new \InvalidArgumentException('non-nullable change_in_payables_and_accrued_expense cannot be null');
        }
        $this->container['change_in_payables_and_accrued_expense'] = $change_in_payables_and_accrued_expense;

        return $this;
    }

    /**
     * Gets change_in_prepaid_assets
     *
     * @return float|null
     */
    public function getChangeInPrepaidAssets()
    {
        return $this->container['change_in_prepaid_assets'];
    }

    /**
     * Sets change_in_prepaid_assets
     *
     * @param float|null $change_in_prepaid_assets <p>{{ChangeInPrepaidAssets}} is any increase or decrease between periods of the prepaid assets.</p>
     *
     * @return self
     */
    public function setChangeInPrepaidAssets($change_in_prepaid_assets)
    {
        if (is_null($change_in_prepaid_assets)) {
            throw new \InvalidArgumentException('non-nullable change_in_prepaid_assets cannot be null');
        }
        $this->container['change_in_prepaid_assets'] = $change_in_prepaid_assets;

        return $this;
    }

    /**
     * Gets change_in_receivables
     *
     * @return float|null
     */
    public function getChangeInReceivables()
    {
        return $this->container['change_in_receivables'];
    }

    /**
     * Sets change_in_receivables
     *
     * @param float|null $change_in_receivables <p>Change In {{Accts_Rec}} relative to the previous period. It is any increase or decrease in the cash a company is owed by its customers.</p>
     *
     * @return self
     */
    public function setChangeInReceivables($change_in_receivables)
    {
        if (is_null($change_in_receivables)) {
            throw new \InvalidArgumentException('non-nullable change_in_receivables cannot be null');
        }
        $this->container['change_in_receivables'] = $change_in_receivables;

        return $this;
    }

    /**
     * Gets change_in_working_capital
     *
     * @return float|null
     */
    public function getChangeInWorkingCapital()
    {
        return $this->container['change_in_working_capital'];
    }

    /**
     * Sets change_in_working_capital
     *
     * @param float|null $change_in_working_capital <p>Working Capital is a measure of a company's short term liquidity or its ability to cover short term liabilities. It is defined as the difference between a company's {{Total_Current_Assets}} and {{Total_Current_Liabilities}}. <br>Working Capital is calculated as: Working Capital = {{Total_Current_Assets}} - {{Total_Current_Liabilities}} <br>{{ChangeInWorkingCapital}} is reported in the cash flow statement since it is one of the major ways in which {{Net_Income}} can differ from operating cash flow.</p>
     *
     * @return self
     */
    public function setChangeInWorkingCapital($change_in_working_capital)
    {
        if (is_null($change_in_working_capital)) {
            throw new \InvalidArgumentException('non-nullable change_in_working_capital cannot be null');
        }
        $this->container['change_in_working_capital'] = $change_in_working_capital;

        return $this;
    }

    /**
     * Gets debt_issuance
     *
     * @return float|null
     */
    public function getDebtIssuance()
    {
        return $this->container['debt_issuance'];
    }

    /**
     * Sets debt_issuance
     *
     * @param float|null $debt_issuance debt_issuance
     *
     * @return self
     */
    public function setDebtIssuance($debt_issuance)
    {
        if (is_null($debt_issuance)) {
            throw new \InvalidArgumentException('non-nullable debt_issuance cannot be null');
        }
        $this->container['debt_issuance'] = $debt_issuance;

        return $this;
    }

    /**
     * Gets debt_payments
     *
     * @return float|null
     */
    public function getDebtPayments()
    {
        return $this->container['debt_payments'];
    }

    /**
     * Sets debt_payments
     *
     * @param float|null $debt_payments debt_payments
     *
     * @return self
     */
    public function setDebtPayments($debt_payments)
    {
        if (is_null($debt_payments)) {
            throw new \InvalidArgumentException('non-nullable debt_payments cannot be null');
        }
        $this->container['debt_payments'] = $debt_payments;

        return $this;
    }

    /**
     * Gets dividends
     *
     * @return float|null
     */
    public function getDividends()
    {
        return $this->container['dividends'];
    }

    /**
     * Sets dividends
     *
     * @param float|null $dividends <p>{{Dividends}} refers to the payment of cash to shareholders as dividends when the company generates income.</p>
     *
     * @return self
     */
    public function setDividends($dividends)
    {
        if (is_null($dividends)) {
            throw new \InvalidArgumentException('non-nullable dividends cannot be null');
        }
        $this->container['dividends'] = $dividends;

        return $this;
    }

    /**
     * Gets effect_of_exchange_rate_changes
     *
     * @return float|null
     */
    public function getEffectOfExchangeRateChanges()
    {
        return $this->container['effect_of_exchange_rate_changes'];
    }

    /**
     * Sets effect_of_exchange_rate_changes
     *
     * @param float|null $effect_of_exchange_rate_changes effect_of_exchange_rate_changes
     *
     * @return self
     */
    public function setEffectOfExchangeRateChanges($effect_of_exchange_rate_changes)
    {
        if (is_null($effect_of_exchange_rate_changes)) {
            throw new \InvalidArgumentException('non-nullable effect_of_exchange_rate_changes cannot be null');
        }
        $this->container['effect_of_exchange_rate_changes'] = $effect_of_exchange_rate_changes;

        return $this;
    }

    /**
     * Gets ending_cash_position
     *
     * @return float|null
     */
    public function getEndingCashPosition()
    {
        return $this->container['ending_cash_position'];
    }

    /**
     * Sets ending_cash_position
     *
     * @param float|null $ending_cash_position ending_cash_position
     *
     * @return self
     */
    public function setEndingCashPosition($ending_cash_position)
    {
        if (is_null($ending_cash_position)) {
            throw new \InvalidArgumentException('non-nullable ending_cash_position cannot be null');
        }
        $this->container['ending_cash_position'] = $ending_cash_position;

        return $this;
    }

    /**
     * Gets issuance_of_stock
     *
     * @return float|null
     */
    public function getIssuanceOfStock()
    {
        return $this->container['issuance_of_stock'];
    }

    /**
     * Sets issuance_of_stock
     *
     * @param float|null $issuance_of_stock <p>A company may raise cash from issuing new shares. It can also use cash to buy back shares. If this number is positive, it means that the company has received more cash from issuing shares than it has paid to buy back shares. If this number is negative, it means that company has paid more cash to buy back shares than it has received for issuing shares.</p>
     *
     * @return self
     */
    public function setIssuanceOfStock($issuance_of_stock)
    {
        if (is_null($issuance_of_stock)) {
            throw new \InvalidArgumentException('non-nullable issuance_of_stock cannot be null');
        }
        $this->container['issuance_of_stock'] = $issuance_of_stock;

        return $this;
    }

    /**
     * Gets net_change_in_cash
     *
     * @return float|null
     */
    public function getNetChangeInCash()
    {
        return $this->container['net_change_in_cash'];
    }

    /**
     * Sets net_change_in_cash
     *
     * @param float|null $net_change_in_cash <p>{{Net_Change_in_Cash}} is calculated as {{Net_Change_in_Cash}} = {{Cash_Flow_from_Operations}} + {{Cash_Flow_from_Investing}} + {{Cash_from_Financing}} + {{effect_of_exchange_rate_changes}}</p>
     *
     * @return self
     */
    public function setNetChangeInCash($net_change_in_cash)
    {
        if (is_null($net_change_in_cash)) {
            throw new \InvalidArgumentException('non-nullable net_change_in_cash cannot be null');
        }
        $this->container['net_change_in_cash'] = $net_change_in_cash;

        return $this;
    }

    /**
     * Gets net_income_from_continuing_operations
     *
     * @return float|null
     */
    public function getNetIncomeFromContinuingOperations()
    {
        return $this->container['net_income_from_continuing_operations'];
    }

    /**
     * Sets net_income_from_continuing_operations
     *
     * @param float|null $net_income_from_continuing_operations <p>{{NetIncomeFromContinuingOperations}} indicates the {{Net_Income}} that a firm brings in from ongoing business activities. These activities are expected to continue into the next reporting period. It excludes extraordinary items, income from the cumulative effects of accounting changes, non-recurring items, income from tax loss carry forward, and {{IS_preferred_dividends}}.</p>
     *
     * @return self
     */
    public function setNetIncomeFromContinuingOperations($net_income_from_continuing_operations)
    {
        if (is_null($net_income_from_continuing_operations)) {
            throw new \InvalidArgumentException('non-nullable net_income_from_continuing_operations cannot be null');
        }
        $this->container['net_income_from_continuing_operations'] = $net_income_from_continuing_operations;

        return $this;
    }

    /**
     * Gets net_intangibles_purchase_and_sale
     *
     * @return float|null
     */
    public function getNetIntangiblesPurchaseAndSale()
    {
        return $this->container['net_intangibles_purchase_and_sale'];
    }

    /**
     * Sets net_intangibles_purchase_and_sale
     *
     * @param float|null $net_intangibles_purchase_and_sale <p>{{NetIntangiblesPurchaseAndSale}} means the net cash inflow received by a company that comes from the purchase and sale of intangibles. It equals the cash received from sale of intangibles minus the cash spent on purchasing intangibles.</p>
     *
     * @return self
     */
    public function setNetIntangiblesPurchaseAndSale($net_intangibles_purchase_and_sale)
    {
        if (is_null($net_intangibles_purchase_and_sale)) {
            throw new \InvalidArgumentException('non-nullable net_intangibles_purchase_and_sale cannot be null');
        }
        $this->container['net_intangibles_purchase_and_sale'] = $net_intangibles_purchase_and_sale;

        return $this;
    }

    /**
     * Gets net_issuance_of_debt
     *
     * @return float|null
     */
    public function getNetIssuanceOfDebt()
    {
        return $this->container['net_issuance_of_debt'];
    }

    /**
     * Sets net_issuance_of_debt
     *
     * @param float|null $net_issuance_of_debt <p>{{Net_Issuance_of_Debt}} is the cash a company received or spent through debt related activities such as debt issuance or debt repayment. If a company pays down its debt during the period, this number will be negative. If a company issued more debt, it receives cash and this number is positive.</p>
     *
     * @return self
     */
    public function setNetIssuanceOfDebt($net_issuance_of_debt)
    {
        if (is_null($net_issuance_of_debt)) {
            throw new \InvalidArgumentException('non-nullable net_issuance_of_debt cannot be null');
        }
        $this->container['net_issuance_of_debt'] = $net_issuance_of_debt;

        return $this;
    }

    /**
     * Gets net_issuance_of_preferred
     *
     * @return float|null
     */
    public function getNetIssuanceOfPreferred()
    {
        return $this->container['net_issuance_of_preferred'];
    }

    /**
     * Sets net_issuance_of_preferred
     *
     * @param float|null $net_issuance_of_preferred <p>A company may raise cash from issuing new preferred shares. It can also use cash to buy back preferred shares. If this number is positive, it means that the company has received more cash from issuing preferred shares than it has paid to buy back preferred shares. If this number is negative, it means that company has paid more cash to buy back preferred shares than it has received for issuing preferred shares.</p>
     *
     * @return self
     */
    public function setNetIssuanceOfPreferred($net_issuance_of_preferred)
    {
        if (is_null($net_issuance_of_preferred)) {
            throw new \InvalidArgumentException('non-nullable net_issuance_of_preferred cannot be null');
        }
        $this->container['net_issuance_of_preferred'] = $net_issuance_of_preferred;

        return $this;
    }

    /**
     * Gets other_financing
     *
     * @return float|null
     */
    public function getOtherFinancing()
    {
        return $this->container['other_financing'];
    }

    /**
     * Sets other_financing
     *
     * @param float|null $other_financing <p>{{Other_Financing}} represents other {{Cash_from_Financing}} activity that not otherwise classified, which includes: Proceeds From Stock Option Exercised, Other Financing Charges.</p>
     *
     * @return self
     */
    public function setOtherFinancing($other_financing)
    {
        if (is_null($other_financing)) {
            throw new \InvalidArgumentException('non-nullable other_financing cannot be null');
        }
        $this->container['other_financing'] = $other_financing;

        return $this;
    }

    /**
     * Gets purchase_of_business
     *
     * @return float|null
     */
    public function getPurchaseOfBusiness()
    {
        return $this->container['purchase_of_business'];
    }

    /**
     * Sets purchase_of_business
     *
     * @param float|null $purchase_of_business <p>{{PurchaseOfBusiness}} is the amount used to purchase business.</p>
     *
     * @return self
     */
    public function setPurchaseOfBusiness($purchase_of_business)
    {
        if (is_null($purchase_of_business)) {
            throw new \InvalidArgumentException('non-nullable purchase_of_business cannot be null');
        }
        $this->container['purchase_of_business'] = $purchase_of_business;

        return $this;
    }

    /**
     * Gets purchase_of_investment
     *
     * @return float|null
     */
    public function getPurchaseOfInvestment()
    {
        return $this->container['purchase_of_investment'];
    }

    /**
     * Sets purchase_of_investment
     *
     * @param float|null $purchase_of_investment <p>{{PurchaseOfInvestment}} represents cash outflow on the purchase of investments in securities.</p>
     *
     * @return self
     */
    public function setPurchaseOfInvestment($purchase_of_investment)
    {
        if (is_null($purchase_of_investment)) {
            throw new \InvalidArgumentException('non-nullable purchase_of_investment cannot be null');
        }
        $this->container['purchase_of_investment'] = $purchase_of_investment;

        return $this;
    }

    /**
     * Gets purchase_of_ppe
     *
     * @return float|null
     */
    public function getPurchaseOfPpe()
    {
        return $this->container['purchase_of_ppe'];
    }

    /**
     * Sets purchase_of_ppe
     *
     * @param float|null $purchase_of_ppe <p>{{PurchaseOfPPE}} is the amount used to purchase Property, Plant and Equipment.</p>
     *
     * @return self
     */
    public function setPurchaseOfPpe($purchase_of_ppe)
    {
        if (is_null($purchase_of_ppe)) {
            throw new \InvalidArgumentException('non-nullable purchase_of_ppe cannot be null');
        }
        $this->container['purchase_of_ppe'] = $purchase_of_ppe;

        return $this;
    }

    /**
     * Gets repurchase_of_stock
     *
     * @return float|null
     */
    public function getRepurchaseOfStock()
    {
        return $this->container['repurchase_of_stock'];
    }

    /**
     * Sets repurchase_of_stock
     *
     * @param float|null $repurchase_of_stock <p>A company may raise cash from issuing new shares. It can also use cash to buy back shares. {{Repurchase_of_Stock}} represents the cash outflow to reacquire common stock during the period.</p>
     *
     * @return self
     */
    public function setRepurchaseOfStock($repurchase_of_stock)
    {
        if (is_null($repurchase_of_stock)) {
            throw new \InvalidArgumentException('non-nullable repurchase_of_stock cannot be null');
        }
        $this->container['repurchase_of_stock'] = $repurchase_of_stock;

        return $this;
    }

    /**
     * Gets sale_of_business
     *
     * @return float|null
     */
    public function getSaleOfBusiness()
    {
        return $this->container['sale_of_business'];
    }

    /**
     * Sets sale_of_business
     *
     * @param float|null $sale_of_business <p>{{SaleOfBusiness}} is the amount earned to sell business.</p>
     *
     * @return self
     */
    public function setSaleOfBusiness($sale_of_business)
    {
        if (is_null($sale_of_business)) {
            throw new \InvalidArgumentException('non-nullable sale_of_business cannot be null');
        }
        $this->container['sale_of_business'] = $sale_of_business;

        return $this;
    }

    /**
     * Gets sale_of_investment
     *
     * @return float|null
     */
    public function getSaleOfInvestment()
    {
        return $this->container['sale_of_investment'];
    }

    /**
     * Sets sale_of_investment
     *
     * @param float|null $sale_of_investment <p>{{SaleOfInvestment}} represents cash inflow on the sale of investments in securities.</p>
     *
     * @return self
     */
    public function setSaleOfInvestment($sale_of_investment)
    {
        if (is_null($sale_of_investment)) {
            throw new \InvalidArgumentException('non-nullable sale_of_investment cannot be null');
        }
        $this->container['sale_of_investment'] = $sale_of_investment;

        return $this;
    }

    /**
     * Gets sale_of_ppe
     *
     * @return float|null
     */
    public function getSaleOfPpe()
    {
        return $this->container['sale_of_ppe'];
    }

    /**
     * Sets sale_of_ppe
     *
     * @param float|null $sale_of_ppe <p>{{SaleOfPPE}} is the amount earned to sell {{Net_PPE}}. </p>
     *
     * @return self
     */
    public function setSaleOfPpe($sale_of_ppe)
    {
        if (is_null($sale_of_ppe)) {
            throw new \InvalidArgumentException('non-nullable sale_of_ppe cannot be null');
        }
        $this->container['sale_of_ppe'] = $sale_of_ppe;

        return $this;
    }

    /**
     * Gets stock_based_compensation
     *
     * @return float|null
     */
    public function getStockBasedCompensation()
    {
        return $this->container['stock_based_compensation'];
    }

    /**
     * Sets stock_based_compensation
     *
     * @param float|null $stock_based_compensation <p>{{StockBasedCompensation}} is a way corporations use stock options to reward employees. It provides executives and employees the opportunity to share in the growth of the company and, if structured properly, can align their interests with the interests of the company's shareholders and investors, without burning the company's cash on hand.</p>
     *
     * @return self
     */
    public function setStockBasedCompensation($stock_based_compensation)
    {
        if (is_null($stock_based_compensation)) {
            throw new \InvalidArgumentException('non-nullable stock_based_compensation cannot be null');
        }
        $this->container['stock_based_compensation'] = $stock_based_compensation;

        return $this;
    }

    /**
     * Gets total_free_cash_flow
     *
     * @return float|null
     */
    public function getTotalFreeCashFlow()
    {
        return $this->container['total_free_cash_flow'];
    }

    /**
     * Sets total_free_cash_flow
     *
     * @param float|null $total_free_cash_flow <p>{{total_freecashflow}} is considered one of the most important parameters to measure a company's earnings power by value investors because it is not subject to estimates of {{DDA}} (DDA). However, when we look at the {{total_freecashflow}}, we should look from a long term perspective, because any year's {{total_freecashflow}} can be drastically affected by the spending on {{Net_PPE}} (PPE) of the business in that year. Over the long term, {{total_freecashflow}} should give pretty good picture on the real earnings power of the company. <br>{{total_freecashflow}} is calculated as {{total_freecashflow}} = {{cash_Flow_from_Operations}} + {{Cash_Flow_CPEX}}</p>
     *
     * @return self
     */
    public function setTotalFreeCashFlow($total_free_cash_flow)
    {
        if (is_null($total_free_cash_flow)) {
            throw new \InvalidArgumentException('non-nullable total_free_cash_flow cannot be null');
        }
        $this->container['total_free_cash_flow'] = $total_free_cash_flow;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


